#!/bin/bash
# Regression test: AmneziaWG v3 obfuscation params.
#
# v3 adds header protection (HeaderProtectionKey), content padding, S3/S4, and
# randomized timings on top of the 1.x baseline (Jc/S1-S2/H1-H4). These are
# generated by amneziawg_ensure_v3_params and must land in both the server
# awg0.conf and every client config. The mandatory-match ones (HeaderProtection
# key + S1-S4) have to be byte-identical between server and client or the tunnel
# silently dies -- this pins that they are emitted, and that a pre-v3 install is
# migrated in place WITHOUT disturbing the H/S values its live peers use.
#
# The exact param syntax is validated against a real `awg setconf` separately
# (that needs the v3 binaries); this is the pure config-gen regression net.
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
pass=0; fail=0
ok()  { printf '  ok    %s\n' "$1"; pass=$((pass+1)); }
bad() { printf '  FAIL  %s\n' "$1"; fail=$((fail+1)); }

echo "AmneziaWG v3 params"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# Source once, assert in this shell (so the counters aggregate). The libs
# hard-assign AWG_CONFIG_DIR / log_* at source time, so overrides come after.
source "$ROOT/scripts/lib/common.sh"
source "$ROOT/scripts/lib/amneziawg.sh"
log_info() { :; }; log_warn() { :; }; log_error() { :; }
# `wg` isn't installed in CI; stub genkey/pubkey to emit a valid base64 wg key.
wg() {
    case "${1:-}" in
        genkey) openssl rand -base64 32 2>/dev/null || head -c 32 /dev/urandom | base64 ;;
        pubkey) cat >/dev/null 2>&1; openssl rand -base64 32 2>/dev/null || head -c 32 /dev/urandom | base64 ;;
    esac
}
is_wgkey() { [[ "$1" =~ ^[A-Za-z0-9+/]{42,43}=$ ]]; }   # 32-byte base64

# --- 1. migration: a pre-v3 env gains v3 params, keeps its H/S untouched ------
export STATE_DIR="$WORK/s1"; AWG_CONFIG_DIR="$WORK/s1/cfg"
mkdir -p "$STATE_DIR/keys" "$AWG_CONFIG_DIR"
cat > "$STATE_DIR/keys/amneziawg.env" <<EOF
AWG_H1=111
AWG_H2=222
AWG_H3=333
AWG_H4=444
AWG_S1=100
AWG_S2=45
AWG_JC=4
AWG_JMIN=50
AWG_JMAX=1000
EOF
amneziawg_ensure_v3_params
env_file="$STATE_DIR/keys/amneziawg.env"
for k in AWG_S3 AWG_S4 AWG_H_KEY AWG_CPA AWG_REKEY_AFTER AWG_REKEY_TIMEOUT \
         AWG_REJECT_AFTER AWG_KEEPALIVE_TIMEOUT AWG_MAX_HANDSHAKE AWG_PKA AWG_RTRAILERS; do
    grep -q "^${k}=" "$env_file" && ok "migration adds $k" || bad "migration missing $k"
done
grep -q '^AWG_H1=111$' "$env_file" && grep -q '^AWG_S1=100$' "$env_file" \
    && ok "migration preserves H1/S1" || bad "migration changed H1/S1"
s3=$(grep '^AWG_S3=' "$env_file" | cut -d= -f2)
s4=$(grep '^AWG_S4=' "$env_file" | cut -d= -f2)
{ [ "$s3" -ge 12 ] && [ "$s4" -ge 12 ]; } && ok "S3/S4 >= 12 ($s3/$s4)" || bad "S3/S4 below 12 ($s3/$s4)"
hk=$(grep '^AWG_H_KEY=' "$env_file" | cut -d= -f2-)   # -f2- keeps the base64 '=' padding
is_wgkey "$hk" && ok "HeaderProtectionKey is a base64 wg key" || bad "HeaderProtectionKey malformed ($hk)"
before=$(wc -l < "$env_file"); amneziawg_ensure_v3_params; after=$(wc -l < "$env_file")
[ "$before" = "$after" ] && ok "ensure_v3_params is idempotent" || bad "ensure_v3_params duplicated ($before->$after)"

# --- 2. server awg0.conf: always-on obf params, gated header protection --------
export STATE_DIR="$WORK/s2"; AWG_CONFIG_DIR="$WORK/s2/cfg"
mkdir -p "$STATE_DIR/keys" "$AWG_CONFIG_DIR"
export SERVER_IP="203.0.113.10"
generate_amneziawg_config >/dev/null 2>&1   # default: header protection OFF
conf="$AWG_CONFIG_DIR/awg0.conf"
# S3/S4 + randomized timings are supported by every client, always emitted.
for key in "S3 =" "S4 =" "RekeyAfterTime =" "RekeyTimeout =" "RejectAfterTime =" \
           "KeepaliveTimeout =" "MaxHandshakeAttempts ="; do
    grep -q "^${key}" "$conf" && ok "awg0.conf has ${key%% *}" || bad "awg0.conf missing ${key%% *}"
done
# The AWG 1.5 header-protection block is OFF by default: the AmneziaVPN app's
# .conf importer drops these keys, so emitting them makes that client connect
# but relay nothing. Regression net for that bug.
for key in "HeaderProtectionKey =" "ContentPaddingAddition =" "RandomTrailers ="; do
    grep -q "^${key}" "$conf" && bad "awg0.conf emits ${key%% *} by default (breaks AmneziaVPN import)" \
        || ok "awg0.conf omits ${key%% *} by default"
done

# --- 2c. AMNEZIAWG_HEADER_PROTECTION=true opts back into the block -------------
export STATE_DIR="$WORK/s2h"; AWG_CONFIG_DIR="$WORK/s2h/cfg"
mkdir -p "$STATE_DIR/keys" "$AWG_CONFIG_DIR"
AMNEZIAWG_HEADER_PROTECTION=true generate_amneziawg_config >/dev/null 2>&1
hconf="$AWG_CONFIG_DIR/awg0.conf"
for key in "HeaderProtectionKey =" "ContentPaddingAddition =" "RandomTrailers ="; do
    grep -q "^${key}" "$hconf" && ok "opt-in emits ${key%% *}" || bad "opt-in missing ${key%% *}"
done

# --- 2b. DisableCookies toggle: absent by default, present when opted in -------
grep -q "^DisableCookies" "$conf" && bad "DisableCookies present by default (should be off)" \
    || ok "DisableCookies off by default (cookies kept on)"
export STATE_DIR="$WORK/s2c"; AWG_CONFIG_DIR="$WORK/s2c/cfg"
mkdir -p "$STATE_DIR/keys" "$AWG_CONFIG_DIR"
AWG_DISABLE_COOKIES=true generate_amneziawg_config >/dev/null 2>&1
grep -q "^DisableCookies = on" "$AWG_CONFIG_DIR/awg0.conf" \
    && ok "AWG_DISABLE_COOKIES=true emits DisableCookies = on" || bad "toggle did not emit DisableCookies"
# restore the default-config path for section 3
export STATE_DIR="$WORK/s2"; AWG_CONFIG_DIR="$WORK/s2/cfg"; conf="$AWG_CONFIG_DIR/awg0.conf"

# --- 3. compat-mode client mirrors the compat server (no header protection) ----
# STATE_DIR/AWG_CONFIG_DIR are the default (compat) server from section 2.
user="tester"
mk_user_env() {   # $1 = STATE_DIR
    mkdir -p "$1/users/$user"
    cat > "$1/users/$user/amneziawg.env" <<EOF
AWG_PRIVATE_KEY=$(wg genkey)
AWG_PUBLIC_KEY=$(wg genkey)
AWG_CLIENT_IP=10.67.67.2
EOF
}
mk_user_env "$STATE_DIR"
out="$WORK/out"; mkdir -p "$out"
amneziawg_generate_client_config "$user" "$out" >/dev/null 2>&1
cconf=$(ls "$out"/*awg*.conf 2>/dev/null | head -1)
if [ -z "$cconf" ]; then
    bad "no client config produced"
else
    for key in "S3 =" "S4 ="; do
        grep -q "^${key}" "$cconf" && ok "client conf has ${key%% *}" || bad "client conf missing ${key%% *}"
    done
    # Mirrors the compat server: the header-protection keys the AmneziaVPN
    # importer drops must NOT be in the bundle either, or client and server
    # disagree on the wire format and the tunnel connects with no traffic.
    for key in "HeaderProtectionKey =" "ContentPaddingAddition =" "RandomTrailers ="; do
        grep -q "^${key}" "$cconf" && bad "compat client conf has ${key%% *} (server omits it)" \
            || ok "compat client conf omits ${key%% *}"
    done
    grep -qE '^PersistentKeepalive = [0-9]+-[0-9]+$' "$cconf" \
        && ok "client conf keepalive is a range" || bad "client conf keepalive not a range"
fi

# --- 3b. header-protection client mirrors the opt-in server, keys match --------
export STATE_DIR="$WORK/s2h"; AWG_CONFIG_DIR="$WORK/s2h/cfg"
mk_user_env "$STATE_DIR"
outh="$WORK/outh"; mkdir -p "$outh"
amneziawg_generate_client_config "$user" "$outh" >/dev/null 2>&1
hcconf=$(ls "$outh"/*awg*.conf 2>/dev/null | head -1)
if [ -z "$hcconf" ]; then
    bad "no header-protection client config produced"
else
    for key in "HeaderProtectionKey =" "ContentPaddingAddition =" "RandomTrailers ="; do
        grep -q "^${key}" "$hcconf" && ok "hdrprot client conf has ${key%% *}" \
            || bad "hdrprot client conf missing ${key%% *}"
    done
    skey=$(awk '/^HeaderProtectionKey/{print $3; exit}' "$hconf")
    ckey=$(awk '/^HeaderProtectionKey/{print $3; exit}' "$hcconf")
    [ -n "$skey" ] && [ "$skey" = "$ckey" ] \
        && ok "client HeaderProtectionKey matches server" || bad "client/server HeaderProtectionKey differ"
fi

echo ""
echo "  passed: $pass   failed: $fail"
[ "$fail" -eq 0 ] || exit 1
